version: '3.6'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 30
#  schema-registry:
#    image: markdj/rs-schema-registry:sha-6eda2e9
#    ports:
#      - 8888:8888
#    environment:
#      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"